/*     */ package com.mchange.v2.c3p0.stmt;
/*     */ 
/*     */ import com.mchange.v2.coalesce.Coalescer;
/*     */ import com.mchange.v2.coalesce.CoalescerFactory;
/*     */ import java.lang.reflect.Method;
/*     */ import java.sql.Connection;
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ final class MemoryCoalescedStatementCacheKey
/*     */   extends StatementCacheKey
/*     */ {
/*  47 */   static final Coalescer keyCoalescer = CoalescerFactory.createCoalescer(true, false);
/*     */   static StatementCacheKey _find(Connection pcon, Method stmtProducingMethod, Object[] args) {
/*     */     int result_set_type, result_set_concurrency, columnIndexes[];
/*     */     String[] columnNames;
/*     */     Integer autogeneratedKeys, resultSetHoldability;
/*  52 */     String stmtText = (String)args[0];
/*  53 */     boolean is_callable = stmtProducingMethod.getName().equals("prepareCall");
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */     
/*  62 */     if (args.length == 1) {
/*     */       
/*  64 */       result_set_type = 1003;
/*  65 */       result_set_concurrency = 1007;
/*  66 */       columnIndexes = null;
/*  67 */       columnNames = null;
/*  68 */       autogeneratedKeys = null;
/*  69 */       resultSetHoldability = null;
/*     */     }
/*  71 */     else if (args.length == 2) {
/*     */       
/*  73 */       Class[] argTypes = stmtProducingMethod.getParameterTypes();
/*  74 */       if (argTypes[1].isArray())
/*     */       {
/*  76 */         Class<?> baseType = argTypes[1].getComponentType();
/*  77 */         if (baseType == int.class) {
/*     */           
/*  79 */           result_set_type = 1003;
/*  80 */           result_set_concurrency = 1007;
/*  81 */           columnIndexes = (int[])args[1];
/*  82 */           columnNames = null;
/*  83 */           autogeneratedKeys = null;
/*  84 */           resultSetHoldability = null;
/*     */         }
/*  86 */         else if (baseType == String.class) {
/*     */           
/*  88 */           result_set_type = 1003;
/*  89 */           result_set_concurrency = 1007;
/*  90 */           columnIndexes = null;
/*  91 */           columnNames = (String[])args[1];
/*  92 */           autogeneratedKeys = null;
/*  93 */           resultSetHoldability = null;
/*     */         } else {
/*     */           
/*  96 */           throw new IllegalArgumentException("c3p0 probably needs to be updated for some new JDBC spec! As of JDBC3, we expect two arg statement producing methods where the second arg is either an int, int array, or String array.");
/*     */         
/*     */         }
/*     */       
/*     */       }
/*     */       else
/*     */       {
/* 103 */         result_set_type = 1003;
/* 104 */         result_set_concurrency = 1007;
/* 105 */         columnIndexes = null;
/* 106 */         columnNames = null;
/* 107 */         autogeneratedKeys = (Integer)args[1];
/* 108 */         resultSetHoldability = null;
/*     */       }
/*     */     
/* 111 */     } else if (args.length == 3) {
/*     */       
/* 113 */       result_set_type = ((Integer)args[1]).intValue();
/* 114 */       result_set_concurrency = ((Integer)args[2]).intValue();
/* 115 */       columnIndexes = null;
/* 116 */       columnNames = null;
/* 117 */       autogeneratedKeys = null;
/* 118 */       resultSetHoldability = null;
/*     */     }
/* 120 */     else if (args.length == 4) {
/*     */       
/* 122 */       result_set_type = ((Integer)args[1]).intValue();
/* 123 */       result_set_concurrency = ((Integer)args[2]).intValue();
/* 124 */       columnIndexes = null;
/* 125 */       columnNames = null;
/* 126 */       autogeneratedKeys = null;
/* 127 */       resultSetHoldability = (Integer)args[3];
/*     */     } else {
/*     */       
/* 130 */       throw new IllegalArgumentException("Unexpected number of args to " + stmtProducingMethod.getName());
/*     */     } 
/*     */ 
/*     */ 
/*     */     
/* 135 */     StatementCacheKey uncanonical = new MemoryCoalescedStatementCacheKey(pcon, stmtText, is_callable, result_set_type, result_set_concurrency, columnIndexes, columnNames, autogeneratedKeys, resultSetHoldability);
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */     
/* 145 */     return (StatementCacheKey)keyCoalescer.coalesce(uncanonical);
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   MemoryCoalescedStatementCacheKey(Connection physicalConnection, String stmtText, boolean is_callable, int result_set_type, int result_set_concurrency, int[] columnIndexes, String[] columnNames, Integer autogeneratedKeys, Integer resultSetHoldability) {
/* 158 */     super(physicalConnection, stmtText, is_callable, result_set_type, result_set_concurrency, columnIndexes, columnNames, autogeneratedKeys, resultSetHoldability);
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public boolean equals(Object o) {
/* 170 */     return StatementCacheKey.equals(this, o);
/*     */   }
/*     */   public int hashCode() {
/* 173 */     return StatementCacheKey.hashCode(this);
/*     */   }
/*     */ }


/* Location:              /Users/bacnam/Projects/TieuLongProject/gameserver/gameServer.jar!/com/mchange/v2/c3p0/stmt/MemoryCoalescedStatementCacheKey.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       1.1.3
 */