/*     */ package com.mchange.v2.c3p0.stmt;
/*     */ 
/*     */ import java.lang.reflect.Method;
/*     */ import java.sql.Connection;
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ final class SimpleStatementCacheKey
/*     */   extends StatementCacheKey
/*     */ {
/*     */   static StatementCacheKey _find(Connection pcon, Method stmtProducingMethod, Object[] args) {
/*     */     int result_set_type, result_set_concurrency, columnIndexes[];
/*     */     String[] columnNames;
/*     */     Integer autogeneratedKeys, resultSetHoldability;
/*  47 */     String stmtText = (String)args[0];
/*  48 */     boolean is_callable = stmtProducingMethod.getName().equals("prepareCall");
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */     
/*  57 */     if (args.length == 1) {
/*     */       
/*  59 */       result_set_type = 1003;
/*  60 */       result_set_concurrency = 1007;
/*  61 */       columnIndexes = null;
/*  62 */       columnNames = null;
/*  63 */       autogeneratedKeys = null;
/*  64 */       resultSetHoldability = null;
/*     */     }
/*  66 */     else if (args.length == 2) {
/*     */       
/*  68 */       Class[] argTypes = stmtProducingMethod.getParameterTypes();
/*  69 */       if (argTypes[1].isArray())
/*     */       {
/*  71 */         Class<?> baseType = argTypes[1].getComponentType();
/*  72 */         if (baseType == int.class) {
/*     */           
/*  74 */           result_set_type = 1003;
/*  75 */           result_set_concurrency = 1007;
/*  76 */           columnIndexes = (int[])args[1];
/*  77 */           columnNames = null;
/*  78 */           autogeneratedKeys = null;
/*  79 */           resultSetHoldability = null;
/*     */         }
/*  81 */         else if (baseType == String.class) {
/*     */           
/*  83 */           result_set_type = 1003;
/*  84 */           result_set_concurrency = 1007;
/*  85 */           columnIndexes = null;
/*  86 */           columnNames = (String[])args[1];
/*  87 */           autogeneratedKeys = null;
/*  88 */           resultSetHoldability = null;
/*     */         } else {
/*     */           
/*  91 */           throw new IllegalArgumentException("c3p0 probably needs to be updated for some new JDBC spec! As of JDBC3, we expect two arg statement producing methods where the second arg is either an int, int array, or String array.");
/*     */         
/*     */         }
/*     */       
/*     */       }
/*     */       else
/*     */       {
/*  98 */         result_set_type = 1003;
/*  99 */         result_set_concurrency = 1007;
/* 100 */         columnIndexes = null;
/* 101 */         columnNames = null;
/* 102 */         autogeneratedKeys = (Integer)args[1];
/* 103 */         resultSetHoldability = null;
/*     */       }
/*     */     
/* 106 */     } else if (args.length == 3) {
/*     */       
/* 108 */       result_set_type = ((Integer)args[1]).intValue();
/* 109 */       result_set_concurrency = ((Integer)args[2]).intValue();
/* 110 */       columnIndexes = null;
/* 111 */       columnNames = null;
/* 112 */       autogeneratedKeys = null;
/* 113 */       resultSetHoldability = null;
/*     */     }
/* 115 */     else if (args.length == 4) {
/*     */       
/* 117 */       result_set_type = ((Integer)args[1]).intValue();
/* 118 */       result_set_concurrency = ((Integer)args[2]).intValue();
/* 119 */       columnIndexes = null;
/* 120 */       columnNames = null;
/* 121 */       autogeneratedKeys = null;
/* 122 */       resultSetHoldability = (Integer)args[3];
/*     */     } else {
/*     */       
/* 125 */       throw new IllegalArgumentException("Unexpected number of args to " + stmtProducingMethod.getName());
/*     */     } 
/*     */ 
/*     */ 
/*     */     
/* 130 */     return new SimpleStatementCacheKey(pcon, stmtText, is_callable, result_set_type, result_set_concurrency, columnIndexes, columnNames, autogeneratedKeys, resultSetHoldability);
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   SimpleStatementCacheKey(Connection physicalConnection, String stmtText, boolean is_callable, int result_set_type, int result_set_concurrency, int[] columnIndexes, String[] columnNames, Integer autogeneratedKeys, Integer resultSetHoldability) {
/* 151 */     super(physicalConnection, stmtText, is_callable, result_set_type, result_set_concurrency, columnIndexes, columnNames, autogeneratedKeys, resultSetHoldability);
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public boolean equals(Object o) {
/* 163 */     return StatementCacheKey.equals(this, o);
/*     */   }
/*     */   public int hashCode() {
/* 166 */     return StatementCacheKey.hashCode(this);
/*     */   }
/*     */ }


/* Location:              /Users/bacnam/Projects/TieuLongProject/gameserver/gameServer.jar!/com/mchange/v2/c3p0/stmt/SimpleStatementCacheKey.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       1.1.3
 */