/*    */ package com.zhonglian.server.common.enums;
/*    */ 
/*    */ public enum Title {
/*  4 */   Nong,
/*  5 */   DroiyanTop,
/*  6 */   DroiyanTopTen,
/*  7 */   ArenaTop,
/*  8 */   ArenaTopTen,
/*  9 */   WingLevel,
/* 10 */   RankWingTop,
/* 11 */   RankLevelTop,
/* 12 */   RankGemTop,
/* 13 */   RechargeTo,
/* 14 */   RankPowerTop,
/* 15 */   RankConsumeTop,
/* 16 */   GoldTo,
/* 17 */   RankDungeonTop,
/* 18 */   Dungeon_1,
/* 19 */   Dungeon_2,
/* 20 */   Dungeon_3,
/* 21 */   Dungeon_4,
/* 22 */   Dungeon_5,
/* 23 */   Dungeon_6,
/* 24 */   Dungeon_7,
/* 25 */   Dungeon_8,
/* 26 */   Dungeon_9,
/* 27 */   Dungeon_10,
/* 28 */   Dungeon_11,
/* 29 */   Dungeon_12,
/* 30 */   Dungeon_13,
/* 31 */   Dungeon_14,
/* 32 */   Dungeon_15,
/* 33 */   Dungeon_16,
/* 34 */   Dungeon_17,
/* 35 */   Dungeon_18,
/* 36 */   Dungeon_19,
/* 37 */   Dungeon_20,
/* 38 */   Dungeon_21,
/* 39 */   Dungeon_22,
/* 40 */   Dungeon_23,
/* 41 */   Dungeon_24,
/* 42 */   Dungeon_25,
/* 43 */   Dungeon_26,
/* 44 */   Dungeon_27,
/* 45 */   RankGuildTopLeader,
/* 46 */   RankGuildTopMember,
/* 47 */   WingRank,
/* 48 */   DungeonRank,
/* 49 */   LevelRank,
/* 50 */   PowerRank,
/* 51 */   DroiyanRank,
/* 52 */   ArtificeRank,
/* 53 */   GuildRank,
/* 54 */   Marry;
/*    */ }


/* Location:              /Users/bacnam/Projects/TieuLongProject/gameserver/gameServer.jar!/com/zhonglian/server/common/enums/Title.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */