package com.zhonglian.server.common.enums;

public enum ActivityType {
    None,
    DailySign,
    FirstRecharge,
    SignInOpenServer,
    SignInPrize,
    WingRank,
    DungeonRank,
    LevelRank,
    PowerRank,
    DroiyanRank,
    ArenaRank,
    GumuRank,
    TianLongRank,
    XiaoyaoRank,
    DailyRecharge,
    AccumRecharge,
    MysteryStore,
    ActivityInstance,
    ResetFirstRecharge,
    AllPeopleReward,
    Lottery,
    VipAward,
    FirstReward,
    AccumConsume,
    DrawPrize,
    ArtificeRank,
    GuildRank,
    SignInSeven,
    AccumDayRecharge,
    LevelReward,
    RedPacket,
    NewFirstReward,
    WorldRecharge,
    WorldConsume,
    WorldTreasure,
    FortuneWheel;
}

